### ISSUE TITLE
sessions not maintained on json routes

### ISSUE THREAD

**Issue by morganrallen** [arc-repos/arc-workflows#43]
The same code using an HTML route would increment the session count.

Test case repo:
https://github.com/morganrallen/arc-sandbox-session-test

**Comment by brianleroux** [comment]
eh mang so sorry it took so long to get to this; was able to reproduce w the steps you gave but think the issue is with cURL not persisting the cookie _idx correctly (was able to verify the sessions are ok in a fork https://github.com/brianleroux/arc-sandbox-session-test that used crummy text/html route to test)
