### ISSUE TITLE
Table updating - manual or automatic

### ISSUE THREAD

**Issue by jonathanstiansen** [arc-repos/arc-workflows#45]
I'm noticing that if you start with a table with say:

```
@tables
user
  userID *String
```

and change it to:

```
@tables
user
  userID *String
  somethingNew **String
```

`npm run create` doesn't actually notice that change and skips. And `npm run deploy` only deploys functions, not table updates - is there a way that table updates are supposed to happen or do we have to do it manually? Is this a feature we should add or is there a reason it's not there?

**Comment by brianleroux** [comment]
Yeah this is great question. You'd have to create a temporary table, migrate the data there, drop the orig table, then create the new table (with the new schema) and then migrate the data there, and then drop the tmp copy table. For now, arc just creates stuff if it doesn't already exist and otherwise skips. 

Could get expensive…WDYT?

**Comment by brianleroux** [comment]
(Closing for now but pls don't hesitate to respond here or ask further questions in more issues or jump in slack and ping me!)
